name: First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:

  check-out-code:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

  Check-and-Setup-docker:
    runs-on: self-hosted
    steps:

      - name: Check if Docker is installed
        run: |
          if command -v docker &>/dev/null; then
            echo "Docker is installed."
          else
            echo "Docker is not installed."
          fi

      - name: Set up Docker
        if: steps.check.outputs.stdout == 'Docker is not installed.'
        uses: docker/setup-buildx-action@v1

      - name: Check Docker version
        run: docker --version

    
  Build-docker-image:
    runs-on: self-hosted
    needs: [check-out-code, Check-and-Setup-docker]
    steps:
      - name: Build docker image
        run: docker build -t my-image:1 .

      - name: Show all docker images
        run: docker images
