name: First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: First Step
        run: |
          if command -v docker &>/dev/null; then
            echo "Docker is installed."
            sudo apt update
            docker run -d -p 80:80 nginx
          else
            echo "Docker is not installed."
          fi
          docker images
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Good bye
        run: python -c 'print("Goodbye World")'
        shell: bash
