name: First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:

  check-out-code:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

  Check-and-Setup-docker:
    runs-on: self-hosted
    steps:

      - name: Check if Docker is installed
        run: |
          if command -v docker &>/dev/null; then
            echo "Docker is installed."
          else
            echo "Docker is not installed."
          fi

      - name: Set up Docker
        if: steps.check.outputs.stdout == 'Docker is not installed.'
        uses: docker/setup-buildx-action@v1

      - name: Check Docker version
        run: docker --version

    
  Build-docker-image:
    runs-on: self-hosted
    needs: [check-out-code, Check-and-Setup-docker]
    steps:
      - name: Build docker image
        run: docker build -t my-image:2 .

      - name: Show all docker images
        run: docker images
  Run-the-Build-Container:
    runs-on: self-hosted
    needs: [Build-docker-image]
    steps:
      - name: delete all running containers
        run:  docker rm -f $(docker ps -aq)

      - name : Run docker Container
        run: docker run -d -p 80:80 my-image:2
  Login-to-dockerHub:
    runs-on: self-hosted
    needs: [Build-docker-image]
    steps:
      - name: Login-to-Dhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASS}}

      - name: Push image to DockerHub
        run: docker push noorulqumar80/my-image:2