name: First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: self-hosted
    steps:

      - name: Check if Docker is installed
        run: |
          if command -v docker &>/dev/null; then
            echo "Docker is installed."
          else
            echo "Docker is not installed."
          fi

      - name: Set up Docker
        if: steps.check.outputs.stdout == 'Docker is not installed.'
        uses: docker/setup-buildx-action@v1

      - name: Check Docker version
        run: docker --version
