name: First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: First Step
        run: docker images
        shell: bash
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Good bye
        run: python -c 'print("Goodbye World")'
        shell: bash
