name: First Workflow
on:
  push:
    branches:
      - main
  workflow: dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "hello World"
        shell: bash
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Good bye
        run: print("Good Bye World")
        shell: python3
